version: '3.1'
#
# There are a number of required environmental variables.  For a new installation, copy and past .env-template as .env
# and change the values as appropriate.
#
services:
  #
  # Core Services (standard/required for any system), can be deployed anywhere
  #
  # These host names can be changed, but must the defaults in dependent systems must be overridden via environment
  # variables.
  #
  pipeline-db:
    image: postgres:9
    hostname: pipeline-db
    ports:
      - "${PIPELINE_DATABASE_PORT}:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./datastore/pipeline:/docker-entrypoint-initdb.d
    command: ["-c", "max_connections=200"]
    networks:
      - back_tier

  pipeline-message-queue:
    image: rabbitmq:3-management
    hostname: pipeline-message-queue
    ports:
      - "${PIPELINE_MESSAGE_API_PORT}:5672"
      - "${PIPELINE_MESSAGE_UI_PORT}:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "mqsecret"
    volumes:
      - mq_data:/var/lib/rabbitmq
    networks:
      - back_tier

  pipeline-metrics:
    image: influxdb:1.5
    hostname: pipeline-metrics
    ports:
      - "${PIPELINE_INFLUX_PORT}:8086"
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    networks:
      - back_tier

  pipeline-grafana:
    image: grafana/grafana:5.1.4
    hostname: pipeline-grafana
    ports:
      - "${PIPELINE_GRAFANA_PORT}:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_NAME: "Janelia"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_log:/var/log/grafana
    networks:
      - back_tier

volumes:
  influx_data:
  influx_config:
  grafana_config:
  grafana_log:
  grafana_data:
  mq_data:
  postgres_data:

networks:
  back_tier:
